### ISSUE TITLE
Including other channels in the dataset like 'speed', 'throttle' or 'break'

### ISSUE THREAD

**Issue by Ajk4** [SullyChen/driving-datasets#3]
Hi @SullyChen , thanks for you contribution!

In the data.txt there are columns for 'steering' and 'timestamp'.

In the blogpost you mentioned about other channels like 'speed', 'throttle' or 'break'.

Would it be possible to also include those additional channels in the data.txt files? And if you also recorded some other types of data those could also be added.

Having those columns would make the dataset applicable in my research.

Cheers!

**Comment by SullyChen** [comment]
Apologies! Though I was able to access these channels, I did not actively collect data on them. I should have in retrospect, but I failed to include this in my code. Sorry for the inconvenience. It may be possible to estimate the speed using optical flow and timestamps, but it will not be very accurate. Sully ChenFrom: Ajk4Sent: Tuesday, November 19, 2019 1:19 AMTo: SullyChen/driving-datasetsCc: SubscribedSubject: [SullyChen/driving-datasets] Including other channels in the dataset like 'speed', 'throttle' or 'break' (#3) Hi, thanks for you contribution!In the data.txt there are columns for 'steering' and 'timestamp'.In the blogpost you mentioned about other channels like 'speed', 'throttle' or 'break'.Would it be possible to also include those additional channels in the data.txt files? This would make the dataset applicable in my research.Cheers!—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
